Module2 task1
htmlacademy-adaptive/2063947-cat-energy-26 pull request #2
Opened 2022-08-01 01:23 UTC by romanetsinna

2022-08-01 08:53 UTC, DoberBober commented on source/catalog.html
> +        <img class="logo__image" src="../source/img/logo-mobile-cat.svg" width="34" height="38" alt="Логотип CAT ENERGY.">
Тут и далее пути неверные:
`./img/logo-mobile-cat.svg`.

2022-08-01 08:54 UTC, DoberBober commented on source/catalog.html
> +      <img class="logo-text__image" src="../source/img/logo-mobile-catenergy.svg" width="101" height="18" alt="Надпись CAT ENERGY.">
Лучше одной картинкой вставить, думаю, а не делить лого и надпись.

2022-08-01 08:54 UTC, DoberBober commented on source/catalog.html
> +            <button class="button product__button" type="submit">Заказать</button>
Ссылка.

2022-08-01 08:55 UTC, DoberBober commented on source/catalog.html
> +            <img class="product__image" src="../source/img/product-chicken-500.jpg" width="68" height="86" alt="Cat Energy PRO 500 г с курицей.">
Оберни в ссылку.

2022-08-01 08:55 UTC, DoberBober commented on source/catalog.html
> +            <h3 class="product__title">Cat Energy PRO 500 г</h3>
Название тоже сделай ссылкой.

2022-08-01 08:55 UTC, DoberBober commented on source/catalog.html
> +        <button class="button show-more__button" type="submit">Показать все</button>
Ссылка.

2022-08-01 08:56 UTC, DoberBober commented on source/catalog.html
> +              <button class="button product__button" type="submit">Заказать</button>
Тоже ссылки.

2022-08-01 08:57 UTC, DoberBober commented on source/catalog.html
> +      <div class="gift gift__wrapper">
Блок и свой же элемент получается.

2022-08-01 08:58 UTC, DoberBober commented on source/catalog.html
> +              <button class="button product__button" type="submit">Заказать</button>
product__button лежит не внутри product.

2022-08-01 08:59 UTC, DoberBober commented on source/form.html
> +      <button class="button selection-container__button" type="submit">Отправить заявку</button>
Внутрь формы.

2022-08-01 09:00 UTC, DoberBober commented on source/index.html
> +      <button class="main-container__program" type="button">
Ссылка.

2022-08-01 09:00 UTC, DoberBober commented on source/index.html
> +      <section class="change-weight lose-weight">
Блоки похудение и набор массы лучше обернуть в див-обёртку.

2022-08-01 09:01 UTC, DoberBober commented on source/index.html
> +            <span class="change-weight__catalog-title">Каталог slim</span>
Текст "каталог slim" тоже часть ссылки.

2022-08-01 09:02 UTC, DoberBober commented on source/index.html
> +            <ul class="example-toggle__list">
ul/li тут не совсем к месту. Всё таки не список.

2022-08-01 09:03 UTC, DoberBober commented on source/index.html
> +                <div>
Тут уже нормальный input range будет, если что, а не имитация на дивах.

2022-08-01 09:03 UTC, DoberBober requested changes
Есть небольшие правки.

2022-08-01 14:42 UTC, romanetsinna commented on source/catalog.html
> +        <img class="logo__image" src="../source/img/logo-mobile-cat.svg" width="34" height="38" alt="Логотип CAT ENERGY.">
Почему именно такой путь?
Т.е. я поняла, что мне не надо в пути прописывать source, т.к. документ .html уже и так в этой папке находится.
Почему нельзя прописать просто img/logo-mobile-cat.svg? Без ./ в начале?
Я помню, что ../ значит вернуться на уровень выше, а что значит ./ ?

2022-08-01 14:52 UTC, romanetsinna commented on source/catalog.html
> +      <img class="logo-text__image" src="../source/img/logo-mobile-catenergy.svg" width="101" height="18" alt="Надпись CAT ENERGY.">
Я разделила, т.к. эту надпись потом в футере как отдельный блок можно вставить. 
Думала, что это как раз в духе БЭМ

2022-08-01 15:03 UTC, romanetsinna commented on source/catalog.html
> +            <button class="button product__button" type="submit">Заказать</button>
Т.е. мы прописываем так?
<a class="button product__button" href="#">Заказать</a>

А потом для класса button прописываем, что эта ссылка выглядит как кнопка, верно?

Вроде помню, а вроде и забыла)))

2022-08-01 15:15 UTC, romanetsinna commented on source/catalog.html
> +            <img class="product__image" src="../source/img/product-chicken-500.jpg" width="68" height="86" alt="Cat Energy PRO 500 г с курицей.">
Обернула, но не уверена теперь в классе, который присвоила тегу а:

`<a class="product__image-link" href="#"><img class="product__image" src="./img/product-chicken-500.jpg" width="68" height="86" alt="Cat Energy PRO 500 г с курицей."></a>`

Может у меня быть элемент product__image, а потом еще элемент product__image-link?
Вроде да, это же 2 разных элемента класса product

2022-08-01 15:21 UTC, romanetsinna commented on source/catalog.html
> +            <h3 class="product__title">Cat Energy PRO 500 г</h3>
Обернула и такой же вопрос по присвоению класса для тега а:

`<a class="product__title-link" href="#"><h3 class="product__title">Cat Energy PRO 500 г</h3></a>`

У меня есть блок product и у него 2 элемента: product__title и product__title-link.
Так нормально?

2022-08-01 15:33 UTC, romanetsinna commented on source/catalog.html
> +              <button class="button product__button" type="submit">Заказать</button>
На главной есть еще кнопка Подобрать программу. Это ведь тоже ссылка?

2022-08-01 15:41 UTC, romanetsinna commented on source/catalog.html
> +      <div class="gift gift__wrapper">
Заменила на:

```
<div class="gift">
    <div class="gift__wrapper">
        <h3 class="visually-hidden">Как получить подарок</h3>
        <p class="gift__text">Закажите все и получите чехол для кота в подарок!</p>
    </div>
</div>
```

2022-08-01 15:41 UTC, romanetsinna commented on source/catalog.html
> +              <button class="button product__button" type="submit">Заказать</button>
Исправила

2022-08-01 15:41 UTC, romanetsinna commented on source/catalog.html
> +        <button class="button show-more__button" type="submit">Показать все</button>
Исправила

2022-08-01 15:42 UTC, romanetsinna commented on source/form.html
> +      <button class="button selection-container__button" type="submit">Отправить заявку</button>
Кнопку вложила внутрь формы, а текст про обязательные поля оставить за формой?

2022-08-01 15:45 UTC, romanetsinna commented on source/index.html
> +      <button class="main-container__program" type="button">
Не понимаю, зачем я так намудрила с классами и span...

В общем, не уверена, но вот этот код:
```
<button class="main-container__program" type="button">
    <span class="main-container__program-text">Подобрать программу</span>
</button>
``` 
я заменила на:

`<a class="button main-container__button" href="#">Подобрать программу</a>`

2022-08-01 15:50 UTC, romanetsinna commented on source/index.html
> +      <section class="change-weight lose-weight">
А того, что они уже в отдельных секциях, недостаточно?
Т.е. у меня будет одна секция change-weight, а внутри нее 2 дива - lose-weight и gain-weight?

Я думала, что, поместив их в 2 разных секции, я и буду ими управлять.

В общем вопрос во взаимном использовании section и div

2022-08-01 15:56 UTC, romanetsinna commented on source/index.html
> +            <span class="change-weight__catalog-title">Каталог slim</span>
Исправила, то же самое с "каталог pro"

2022-08-01 16:00 UTC, romanetsinna commented on source/index.html
> +            <ul class="example-toggle__list">
Изменила вот так:
```
<div class="example-toggle">
    <img class="example-toggle__image" src="./img/before-cat-mobile.jpg" width="280" height="232" alt="Фото кота до программы.">
    <div class="example-toggle__range">
        <span class="example-toggle__item">Было</span>
        <span class="example-toggle__item">Стало</span>
    </div>
</div>
```
Но что-то я не понимаю, как эту штучку зеленую между ними вставлять

2022-08-01 16:12 UTC, romanetsinna commented on source/index.html
> +                <div>
```
<div class="example-toggle">
    <img class="example-toggle__image" src="./img/before-cat-mobile.jpg" width="280" height="232" alt="Фото кота до программы.">
    <div class="example-toggle__range">
    <span class="example-toggle__item">Было</span>
        <div>
            <input type="range" id="before-after" name="before-after" min="" max="">
            <label class="visually-hidden" for="before-after">Было-Стало</label>
        </div>
    <span class="example-toggle__item">Стало</span>
    </div>
 </div>
```

Вот так пока что оставила

2022-08-01 21:27 UTC, DoberBober commented on source/catalog.html
> +        <img class="logo__image" src="../source/img/logo-mobile-cat.svg" width="34" height="38" alt="Логотип CAT ENERGY.">
`./` указывает на текущую папку. Можно и без него, в принципе. Но явное указание, как по мне, лучше.

2022-08-01 21:28 UTC, DoberBober commented on source/catalog.html
> +      <img class="logo-text__image" src="../source/img/logo-mobile-catenergy.svg" width="101" height="18" alt="Надпись CAT ENERGY.">
Просто в шапке картинка логотипа меняется и будет легче, если сделать эти две части единым логотипом. Про то, как менять, расскажут на лекции про адаптивные картинки.

2022-08-01 21:29 UTC, DoberBober commented on source/catalog.html
> +            <button class="button product__button" type="submit">Заказать</button>
Ага. В стилях как оформишь и какие стили накинешь - дело второе. Главное, чтобы этот тег был ссылкой.

2022-08-01 21:29 UTC, DoberBober commented on source/catalog.html
> +            <img class="product__image" src="../source/img/product-chicken-500.jpg" width="68" height="86" alt="Cat Energy PRO 500 г с курицей.">
Да, всё хорошо в твоём примере. product__image и product__image-link могут быть, с этим никаких проблем.

2022-08-01 21:30 UTC, DoberBober commented on source/catalog.html
> +            <h3 class="product__title">Cat Energy PRO 500 г</h3>
Норм. Но я бы лучше вложил ссылку внутрь заголовка, а не наоборот. Есть одно небольшое различие. Посмотри оба варианта и попробуй догадаться.)) Если не получится - напиши, я объясню.

2022-08-01 21:32 UTC, DoberBober commented on source/form.html
> +      <button class="button selection-container__button" type="submit">Отправить заявку</button>
Текст поставь туда, где тебе будет удобнее сверстать. Скорее всего, тоже внутри формы окажется в конечном итоге, но тут не принципиальный момент. Поэтому пока можно на этом не зацикливаться.

2022-08-01 21:33 UTC, DoberBober commented on source/index.html
> +      <section class="change-weight lose-weight">
Можешь пока что и оставить, в принципе. Просто вопрос как ты их поставишь в один ряд. Если дашь общую обёртку, то этой обёртке просто пропишешь флекс и всё. А так придётся возиться. Ну и плюс ты группируешь два похожих элемента.

2022-08-01 21:34 UTC, DoberBober commented on source/index.html
> +            <ul class="example-toggle__list">
Было/стало кнопками лучше сделай. Остальное пока норм.

2022-08-02 02:34 UTC, romanetsinna commented on source/catalog.html
> +      <img class="logo-text__image" src="../source/img/logo-mobile-catenergy.svg" width="101" height="18" alt="Надпись CAT ENERGY.">
Меня смущает только то, что в планшетной и десктопной версии лого и надпись находятся рядом.
А в мобильной версии лого слева, а надпись по центру.
Если я их сейчас сохраню как одну картинку, как мне потом их раздвинуть в планшетной и десктопной версии?

2022-08-02 03:00 UTC, romanetsinna commented on source/catalog.html
> +            <h3 class="product__title">Cat Energy PRO 500 г</h3>
Понятно, все дело в области клика :)

Меняю на:
```
<h3 class="product__title">
  <a class="product__title-link" href="#">Cat Energy PRO 500 г</a>
</h3>
```

2022-08-02 12:32 UTC, merged